export const intentActions = {
	INTENT_RECEIVED: 'LIBRARY-INTENT-CHANNEL#INTENT_RECEIVED',
	UPDATE_CONTEXT: 'LIBRARY-INTENT-CHANNEL#UPDATE_CONTEXT',
	CONTEXT_RECEIVED: 'LIBRARY-INTENT-CHANNEL#CONTEXT_RECEIVED',
	REGISTER_TRANSLATOR: 'LIBRARY-INTENT-CHANNEL#REGISTER_TRANSLATOR',
	REMOVE_TRANSLATOR: 'LIBRARY-INTENT-CHANNEL#REMOVE_TRANSLATOR',
	SEND_INTENT: 'LIBRARY-INTENT-CHANNEL#SEND_INTENT',
	SET_ACTIVE_CONTEXT: 'LIBRARY-INTENT-CHANNEL#SET_ACTIVE_CONTEXT',
	UNSET_ACTIVE_CONTEXT: 'LIBRARY-INTENT-CHANNEL#UNSET_ACTIVE_CONTEXT',
	SEND_INTENT_FEEDBACK: 'LIBRARY-INTENT-CHANNEL#SEND_INTENT_FEEDBACK',
	CREATE_CONVERSATION_WITH_SKILL:
		'LIBRARY-INTENT-CHANNEL#CREATE_CONVERSATION_WITH_SKILL',
	SEND_SYSTEM_MESSAGE: 'LIBRARY-INTENT-CHANNEL#SEND_SYSTEM_MESSAGE',
	INTENT_FEEDBACK_RECEIVED: 'LIBRARY-INTENT-CHANNEL#INTENT_FEEDBACK_RECEIVED',
	CONVERSATION_WITH_SKILL_REQUESTED:
		'LIBRARY-INTENT-CHANNEL#CONVERSATION_WITH_SKILL_REQUESTED',
	SYSTEM_MESSAGE_RECEIVED: 'LIBRARY-INTENT-CHANNEL#SYSTEM_MESSAGE_RECEIVED'
};

export const intentLocalStorageKeys = {
	sendIntent: 'sn_library_intent.send_intent',
	updateContext: 'sn_library_intent.update_context',
	activeTranslatorKey: 'sn_library_intent.active_translator',
	sendIntentFeedback: 'sn_library_intent.send_intent_feedback',
	requestConversationWithSkill:
		'sn_library_intent.request_conversation_with_skill',
	sendSystemMessage: 'sn_library_intent.send_system_message'
};
