/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './src/components/**/*.{js,jsx,ts,tsx}',
  ],
  safelist: [
    'focus-visible:border-ring',
    'focus-visible:ring-ring/50',
    'focus-visible:ring-[3px]',
    'border-input',
    'placeholder:text-muted-foreground',
    'aria-invalid:ring-destructive/20',
    'dark:aria-invalid:ring-destructive/40',
    'aria-invalid:border-destructive',
    'dark:bg-input/30',
    'shadow-xs',
    'bg-primary',
    'text-primary-foreground',
    'hover:bg-primary/90',
    'bg-secondary',
    'text-secondary-foreground',
    'hover:bg-secondary/80',
    'bg-accent',
    'text-accent-foreground',
    'hover:bg-accent',
    'dark:hover:bg-accent/50',
    'bg-destructive',
    'hover:bg-destructive/90',
    'focus-visible:ring-destructive/20',
    'dark:focus-visible:ring-destructive/40',
    'dark:bg-destructive/60',
    'bg-background',
    'hover:bg-accent',
    'hover:text-accent-foreground',
    'dark:bg-input/30',
    'dark:border-input',
    'dark:hover:bg-input/50',
    'text-primary',
    'underline-offset-4',
    'hover:underline',
    'size-9',
    'h-9',
    'px-4',
    'py-2',
    'has-[>svg]:px-3',
    'h-8',
    'gap-1.5',
    'px-3',
    'has-[>svg]:px-2.5',
    'h-10',
    'px-6',
    'has-[>svg]:px-4',
    'min-h-16',
    'md:text-sm',
    'text-base',
    'rounded-md',
    'px-3',
    'py-2',
    'text-sm',
    'font-medium',
    'transition-all',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
    '[&_svg]:pointer-events-none',
    '[&_svg:not([class*=\'size-\'])]:size-4',
    '[&_svg]:shrink-0',
    'outline-none',
    'field-sizing-content',
    'resize-none'
  ],
  theme: {
    extend: {
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
      },
    },
  },
  plugins: [],
}