export const ON_SUBMIT = 'ON_SUBMIT';
export const GFORM_EVENT_CHANGED = 'changed';
export const GFORM_EVENT_CHANGE = 'change';
export const GFORM_EVENT_SUBMITTED = 'submitted';
export const GFORM_ON_PROP_CHANGE = 'onPropertyChange';

export const CATALOG_FORM_SUBMITTED = 'SN_CATALOG_FORM#SUBMITTED';
export const CATALOG_FORM_CHANGED = 'SN_CATALOG_FORM#CHANGED';
export const CATALOG_FORM_FIELD_PROP_CHANGED =
	'SN_CATALOG_FORM#FIELD_PROP_CHANGED';
export const CATALOG_FORM_UI_MESSAGE_SET = 'SN_CATALOG_FORM#UI_MESSAGE_SET';
export const CATALOG_FORM_UI_MESSAGES_CLEARED =
	'SN_CATALOG_FORM#UI_MESSAGES_CLEARED';
