export const GFORM_SET_VALUE = 'GFORM#SET_VALUE';
export const GFORM_SHOW_FIELD_MESSAGE = 'GFORM#SHOW_FIELD_MESSAGE';
export const GFORM_HIDE_FIELD_MESSAGE = 'GFORM#HIDE_FIELD_MESSAGE';
export const GFORM_INTERNAL_SET_FIELD_INVALID =
	'GFORM_INTERNAL#SET_FIELD_INVALID';
export const GFORM_INTERNAL_SET_ADDITIONAL_FIELD_STATE =
	'GFORM#SET_ADDITIONAL_FIELD_STATE';
export const GFORM_ADD_ERROR_MESSAGE = 'GFORM#ADD_ERROR_MESSAGE';
export const GFORM_INTERNAL_BATCH_ACTIONS = 'GFORM_INTERNAL#BATCH_ACTIONS';
