const JSON_LITERAL = 'JSON_LITERAL';
const SHORTHAND = 'SHORTHAND';
const CONTEXT_BINDING = 'CONTEXT_BINDING';
const STATE_BINDING = 'STATE_BINDING';
const ELEMENT_BINDING = 'ELEMENT_BINDING';
const DATA_CHAIN_BINDING = 'DATA_CHAIN_BINDING';
const DATA_OUTPUT_BINDING = 'DATA_OUTPUT_BINDING';
const EVENT_PAYLOAD_BINDING = 'EVENT_PAYLOAD_BINDING';
const VIEWPORT_BINDING = 'VIEWPORT_BINDING';
const REPEATER_ITEM_BINDING = 'REPEATER_ITEM_BINDING';
const CLIENT_TRANSFORM = 'CLIENT_TRANSFORM';
const BINARY = 'BINARY';
const UNARY = 'UNARY';
const RUNTIME_INLINE_SCRIPT = 'RUNTIME_INLINE_SCRIPT';
const MAP_CONTAINER = 'MAP_CONTAINER';
const LIST_CONTAINER = 'LIST_CONTAINER';
const TRANSLATION_LITERAL = 'TRANSLATION_LITERAL';
const UXF_VIEWPORT_RENDER = 'UXF_VIEWPORT#RENDER';
const UXF_VIEWPORT_RENDER_BY_ID = 'UXF_VIEWPORT#RENDER_BY_ID';
const UXF_VIEWPORT_DISMISS = 'UXF_VIEWPORT#DISMISS';
const UXF_VIEWPORT_SCRIPTED_CONDITIONS_EVALUATION_REQUESTED =
	'UXF_VIEWPORT#SCRIPTED_CONDITIONS_EVALUATION_REQUESTED';
const UXF_VIEWPORT_SCRIPTED_CONDITIONS_EVALUATION_COMPLETED =
	'UXF_VIEWPORT#SCRIPTED_CONDITIONS_EVALUATION_COMPLETED';
const UXF_VIEWPORT_CALCULATE_ROUTES = 'UXF_VIEWPORT#CALCULATE_ROUTES';
const UXF_VIEWPORT_ROUTE_INITIALIZATION_COMPLETED =
	'UXF_VIEWPORT#ROUTE_INITIALIZATION_COMPLETED';
const UXF_VIEWPORT_ROUTE_SCRIPTED_CONDITIONS_EVALUATION_COMPLETED =
	'UXF_VIEWPORT#ROUTE_SCRIPTED_CONDITIONS_EVALUATION_COMPLETED';
const UXF_VIEWPORT_ROUTE_SCRIPTED_CONDITIONS_EVALUATION_REQUESTED =
	'UXF_VIEWPORT#ROUTE_SCRIPTED_CONDITIONS_EVALUATION_REQUESTED';

export const propertyTypes = {
	CONTEXT_BINDING,
	STATE_BINDING,
	ELEMENT_BINDING,
	JSON_LITERAL,
	SHORTHAND,
	DATA_CHAIN_BINDING,
	DATA_OUTPUT_BINDING,
	EVENT_PAYLOAD_BINDING,
	VIEWPORT_BINDING,
	REPEATER_ITEM_BINDING,
	CLIENT_TRANSFORM,
	BINARY,
	UNARY,
	RUNTIME_INLINE_SCRIPT,
	MAP_CONTAINER,
	LIST_CONTAINER,
	TRANSLATION_LITERAL
};

const SCRIPT_EXEC_REQUESTED = 'UXF_INTERNAL#SCRIPT_EXEC_REQUESTED';
const MACROPONENT_STATE_UPDATED = 'UXF_INTERNAL#MACROPONENT_STATE_UPDATED';
const WRAPPED_EVENT_REDISPATCH = 'UXF_INTERNAL#WRAPPED_EVENT_REDISPATCH';

const MACROPONENT_READY = 'MACROPONENT_READY';
const MACROPONENT_PROPERTY_CHANGED = 'MACROPONENT_PROPERTY_CHANGED';
const MACROPONENT_VIEWPORT_LOAD_REQUESTED =
	'MACROPONENT_VIEWPORT_LOAD_REQUESTED';
const MACROPONENT_VIEWPORT_LOAD_COMPLETED =
	'MACROPONENT_VIEWPORT_LOAD_COMPLETED';
const MACROPONENT_STATE_UPDATE_REQUESTED = 'MACROPONENT_STATE_UPDATE_REQUESTED';
const MACROPONENT_VIEWPORT_ROUTE_INITIALIZATION_COMPLETED =
	'MACROPONENT_VIEWPORT_ROUTE_INITIALIZATION_COMPLETED';

export const viewportActions = {
	UXF_VIEWPORT_RENDER,
	UXF_VIEWPORT_RENDER_BY_ID,
	UXF_VIEWPORT_DISMISS,
	UXF_VIEWPORT_SCRIPTED_CONDITIONS_EVALUATION_COMPLETED,
	UXF_VIEWPORT_SCRIPTED_CONDITIONS_EVALUATION_REQUESTED,
	UXF_VIEWPORT_CALCULATE_ROUTES,
	UXF_VIEWPORT_ROUTE_INITIALIZATION_COMPLETED,
	UXF_VIEWPORT_ROUTE_SCRIPTED_CONDITIONS_EVALUATION_COMPLETED,
	UXF_VIEWPORT_ROUTE_SCRIPTED_CONDITIONS_EVALUATION_REQUESTED
};

export const HEADLESS_VIEWPORT_COMPONENT_TAG = 'now-uxf-viewport';
export const HEADLESS_VIEWPORT_COMPONENT_PROP_VALUES = {
	headless: true
};

export const internalActions = {
	SCRIPT_EXEC_REQUESTED,
	MACROPONENT_STATE_UPDATED,
	WRAPPED_EVENT_REDISPATCH,
	...viewportActions
};

export const MACROPONENT_FEATURES = {
	DATA_BROKERS: 'DATA_BROKERS',
	VIEWPORTS: 'VIEWPORTS',
	EVENT_MAPPING: 'EVENT_MAPPING'
};

export const MACROPONENT_NODE_PROPERTIES = {
	DATA_BROKERS: 'dataBrokers',
	EVENT_MAPPINGS: 'eventMappings',
	IS_HEADLESS: 'isHeadless',
	IS_HERO: 'isHero',
	IS_HIDDEN: 'isHidden',
	IS_NON_DESTRUCTIVE: 'isNonDestructive',
	LAYOUT_JSON: 'layoutJson',
	NODE_ID: 'nodeId',
	PROPERTIES: 'properties',
	PROPERTY_VALUES: 'propertyValues',
	SHELL: 'shell',
	SLOT: 'slot',
	STATE_PROPERTIES: 'stateProperties',
	STYLES: 'styles',
	TAG_NAME: 'tagName',
	TYPE: 'type'
};

export const UXF_META_PROP_NAME_PREFIX = 'now-uxf';
export const SELECTABLE_PROP_RESOLVER_PROP_NAME_PREFIX =
	UXF_META_PROP_NAME_PREFIX + '-spp';

export const DBK_NAMESPACE_PROP_NAME_PREFIX = UXF_META_PROP_NAME_PREFIX + '-db';
export const DBK_LIFECYCLE_FETCHING_KEY = 'fetching';
export const DBK_LIFECYCLE_FETCH_SUCCESS_KEY = 'fetch-success';
export const MODAL_SELECTED = 'MODAL_SELECTED';
export const DA_WRAPPED_CLICKED = 'DA_WRAPPED_CLICKED';

/**
 * Actions that the macroponent dispatches. Part of UXF's public API.
 * These don't bubble up and so far are limited to lifecycle-type actions.
 */
export const publicDispatchedActionNames = {
	MACROPONENT_READY,
	MACROPONENT_PROPERTY_CHANGED,
	MACROPONENT_VIEWPORT_LOAD_COMPLETED,
	MACROPONENT_VIEWPORT_ROUTE_INITIALIZATION_COMPLETED
};

/**
 * Actions that the macroponent handles. Part of UXF's public API.
 */
export const publicActionHandlerNames = {
	MACROPONENT_STATE_UPDATE_REQUESTED,
	MACROPONENT_VIEWPORT_LOAD_REQUESTED
};

export const IS_INTERNAL_ACTION = Symbol('isUxfInternalAction');

export const IS_MACROPONENT_READY = Symbol('isReady');

export const IS_SOURCED_FROM_SET_STATE = Symbol('isSourcedFromSetState');

export const SEISMIC_STATE_KEY_BEHAVIORS = 'behaviors';

export const CONTAINING_MACROPONENT_SYS_ID = Symbol(
	'DO_NOT_USE__uxfContainingMacropopnentSysId'
);

export const COMPOSITION_ELEMENT_ID = Symbol('DO_NOT_USE__uxfCompositionElId');

export const REPEATER_ITEM = Symbol('repeaterItem');

export const SIGNAL_VIEWPORT_LOAD_COMPLETION = Symbol(
	'DO_NOT_USE__signalViewportLoadCompletion'
);

export const SIGNAL_VIEWPORT_ROUTE_INITIALIZATION_COMPLETION = Symbol(
	'DO_NOT_USE__signalViewportRouteInitializationCompletion'
);

export const PROXY_DATA_ELEMNT_ID = Symbol('uxfProxyDataResourceElId');

export const DATA_ELEMENT_ID = 'dataElemId';

export const MACROPONENT_ROOT_COMPONENT_ID = 'root';

export const CONTEXT_PROPS_IDENTIFIER = 'props';

export const APP_PROPS_IDENTIFIER = 'app';

export const SYS_PROPS_IDENTIFIER = 'sysprop';

export const DBK_OUTPUT_IDENTIFIER = 'output';

export const DBK_LIFECYCLE_IDENTIFIER = 'lifecycle';

export const DBK_LIFECYCLE_FETCHING_IDENTIFIER = 'fetchInProgress';

export const DBK_LIFECYCLE_FETCH_SUCCESS_IDENTIFIER = 'lastFetchSucceeded';

export const SESSION = 'session';

export const UXF_VIEWPORT_SCREEN_TAG = 'sn-uxf-viewport-screen';

export const UXF_INTERNAL_EVENT_META = '__uxfMetaInternalOnlyDoNotUse';

export const UXF_THEME_UPDATED = '__DO_NOT_USE__UXF_INTERNAL#THEME_UPDATED';
