/*
 * Creates an object with the same keys as object and values generated by running
 * each own enumerable string keyed property of object thru iteratee.
 * The iteratee is invoked with three arguments: (value, key, object).
 *
 * @param {Object} object The object to be mapped.
 * @param {*} iteratee String property or function to map object value.
 * @returns {Object} Returns new mapped object
 */
export default function mapValues(object, iteratee) {
	if (iteratee != null && typeof iteratee !== 'function')
		return mapValues(object, (value) => {
			const {[iteratee]: newValue} = value;
			return newValue;
		});

	if (!iteratee) return mapValues(object, (v) => v);

	let result = {};
	if (!object) return result;

	for (const [key, value] of Object.entries(object)) {
		result[key] = iteratee(value, key, object);
	}

	return result;
}
