export const ADD_BUTTON_CLICKED = 'ADD_BUTTON_CLICKED';
export const REMOVE_BUTTON_CLICKED = 'REMOVE_BUTTON_CLICKED';
export const LIST_OPEN_PANEL = 'QUICK_EDIT_CLICKED';
export const GRID_CHECKBOX_TOGGLED = 'GRID_CHECKBOX_TOGGLED';
export const MULTI_ROW_FORM_MODAL_CLOSED = 'MULTI_ROW_FORM_MODAL_CLOSED';
export const UPDATE_MULTI_ROW_DATA = 'UPDATE_MULTI_ROW_DATA';
export const UPDATE_MULTI_ROW_DATA_DISPLAY_VALUES_FETCHED =
	'UPDATE_MULTI_ROW_DATA_DISPLAY_VALUES_FETCHED';
export const ROW_DATA_UPDATED = 'ROW_DATA_UPDATED';
export const DISPLAY_VALUE_REQUESTED = 'DISPLAY_VALUE_REQUESTED';
export const DISPLAY_VALUE_FETCHED = 'DISPLAY_VALUE_FETCHED';
export const DISPLAY_VALUE_REQUESTED_ROW = 'DISPLAY_VALUE_REQUESTED_ROW';
export const REMOVE_MODAL_CLICKED = 'REMOVE_MODAL_CLICKED';
export const REMOVE_MODAL_CLOSED = 'REMOVE_MODAL_CLOSED';
export const DISMISS_REMOVE_MODAL = 'NOW_MODAL#OPENED_SET';
