const CONTEXT_BINDING = 'CONTEXT_BINDING';
const ELEMENT_BINDING = 'ELEMENT_BINDING';
const JSON_LITERAL = 'JSON_LITERAL';
const DATA_CHAIN_BINDING = 'DATA_CHAIN_BINDING';

const UXF_DB_DATA_REQUESTED = 'UXF_DB_DATA_REQUESTED';
const UXF_DB_REFRESH_REQUESTED = 'UXF_DB_REFRESH_REQUESTED';
const UXF_DB_REFRESH_RELATED_REQUESTED = 'UXF_DB_REFRESH_RELATED_REQUESTED';
const UXF_DB_OP_TRIGGER_REQUESTED = 'UXF_DB_OP_TRIGGER_REQUESTED';
const UXF_DB_OP_EXEC_REQUESTED = 'UXF_DB_OP_EXEC_REQUESTED';
const UXF_DB_DATA_RECEIVED = 'UXF_DB_DATA_RECEIVED';
const UXF_DB_BOOTSTRAPPED = 'UXF_DB_BOOTSTRAPPED';
const UXF_DB_INPUT_CHANGED = 'UXF_DB_INPUT_CHANGED';
const UXF_DB_REFRESH_REQUESTED_INITIAL_VALUE =
	'UXF_DB_REFRESH_REQUESTED_INITIAL_VALUE';

// Standard Metadata-driven Broker Lifecycle events, that UIB can
// hang Event Mappings off of -- these cannot change since they are
// part of a public convention/contract
const DATA_FETCH_INITIATED = 'DATA_FETCH_INITIATED';
const DATA_FETCH_SUCCEEDED = 'DATA_FETCH_SUCCEEDED';
const DATA_FETCH_FAILED = 'DATA_FETCH_FAILED';
const DATA_OP_INITIATED = 'DATA_OP_INITIATED';
const DATA_OP_SUCCEEDED = 'DATA_OP_SUCCEEDED';
const DATA_OP_FAILED = 'DATA_OP_FAILED';

const DB_ENGINE_EXEC_REQUESTED = 'UXF_DB_ENGINE_EXEC_REQUESTED';
const DB_ENGINE_EXEC_REQUESTED_WITH_RECORDING =
	'UXF_DB_ENGINE_EXEC_REQUESTED_WITH_RECORDING';
const DB_ENGINE_EXEC_SUCCEEDED = 'UXF_DB_ENGINE_EXEC_SUCCEEDED';
const DB_ENGINE_EXEC_STARTED = 'UXF_DB_ENGINE_EXEC_STARTED';
const DB_ENGINE_EXEC_FAILED = 'UXF_DB_ENGINE_EXEC_FAILED';
const DB_ENGINE_EXEC_PROGRESSED = 'UXF_DB_ENGINE_EXEC_PROGRESSED';

export const DB_TYPE_CLIENT_STATE = 'CLIENT_STATE';
export const DB_GQL_TRANSPORT_PROPERTY =
	'glide.uxf.lib.enable_dbk_graphql_transport';

export const propertyTypes = {
	CONTEXT_BINDING,
	ELEMENT_BINDING,
	JSON_LITERAL,
	DATA_CHAIN_BINDING
};

export const actionTypesAllowedFromScript = [UXF_DB_OP_TRIGGER_REQUESTED];

export const actionTypes = {
	UXF_DB_DATA_REQUESTED,
	UXF_DB_REFRESH_REQUESTED,
	UXF_DB_REFRESH_REQUESTED_INITIAL_VALUE,
	UXF_DB_REFRESH_RELATED_REQUESTED,
	UXF_DB_OP_EXEC_REQUESTED,
	UXF_DB_OP_TRIGGER_REQUESTED,
	UXF_DB_DATA_RECEIVED,
	UXF_DB_BOOTSTRAPPED,
	UXF_DB_INPUT_CHANGED,
	DB_ENGINE_EXEC_REQUESTED,
	DB_ENGINE_EXEC_REQUESTED_WITH_RECORDING,
	DB_ENGINE_EXEC_SUCCEEDED,
	DB_ENGINE_EXEC_STARTED,
	DB_ENGINE_EXEC_FAILED,
	DB_ENGINE_EXEC_PROGRESSED,
	DATA_FETCH_INITIATED,
	DATA_FETCH_SUCCEEDED,
	DATA_FETCH_FAILED,
	DATA_OP_INITIATED,
	DATA_OP_SUCCEEDED,
	DATA_OP_FAILED
};
