export const FOOTER_ACTION_CLICKED = 'NOW_MODAL#FOOTER_ACTION_CLICKED';
export const MODAL_OPENED_SET = 'NOW_MODAL#OPENED_SET';
export const OPEN_DIRTY_MODAL = 'OPEN_DIRTY_MODAL';
export const CALLBACK_CALLED = 'CALLBACK_CALLED';
