export const G_FORM = 'g_form';
export const G_MODAL = 'g_modal';
export const G_SCRATCHPAD = 'g_scratchpad';
export const G_UI_ACTIONS = 'g_ui_actions';
export const G_USER = 'g_user';
export const G_UI_SCRIPTS = 'g_ui_scripts';

export const FORM_LAYOUT_DATA_FETCH_SUCESS =
	'SN_CATALOG_ENVIRONMENT#FORM_LAYOUT_DATA_FETCH_SUCESS';
export const FORM_LAYOUT_DATA_FETCH_ERROR =
	'SN_CATALOG_ENVIRONMENT#FORM_LAYOUT_DATA_FETCH_ERROR';
export const CATALOG_FORM_INITIALIZE_FAILED = 'SN_CATALOG_FORM_ENV#INIT_FAILED';
export const CATALOG_FORM_INITIALIZE_SUCCESS =
	'SN_CATALOG_FORM_ENV#INIT_SUCESS';
export const VARIABLE_INTERNAL_TYPES = {
	BREAK: '12',
	CHECKBOX: '7',
	CONTAINER_END: '20',
	CONTAINER_SPLIT: '24',
	CONTAINER_START: '19',
	DATE: '9',
	DATE_TIME: '10',
	DURATION: '29',
	EMAIL: '26',
	HTML: '23',
	IP_ADDRESS: '28',
	LABEL: '11',
	LIST_COLLECTOR: '21',
	LOOKUP_MULTIPLE_CHOICE: '22',
	LOOKUP_SELECT_BOX: '18',
	MACRO: '14',
	MACRO_WITH_LABEL: '17',
	MASKED: '25',
	MULTI_LINE_TEXT: '2',
	MULTIPLE_CHOICE: '3',
	NUMERIC_SCALE: '4',
	REFERENCE: '8',
	SELECT_BOX: '5',
	SINGLE_LINE_TEXT: '6',
	UI_PAGE: '15',
	URL: '27',
	WIDE_SINGLE_LINE_TEXT: '16',
	YES_NO: '1'
};
