export const SN_RECORD_CHOICE = {
	FOCUS_SET: 'SN_RECORD_CHOICE#FOCUS_SET'
};

export const NOW_DROPDOWN_CUSTOM_TARGET = {
	SELECTED_ITEMS_SET: 'NOW_DROPDOWN_CUSTOM_TARGET#SELECTED_ITEMS_SET',
	OPENED_SET: 'NOW_DROPDOWN_CUSTOM_TARGET#OPENED_SET'
};

export const NOW_DROPDOWN_LIST = {
	ITEM_CLICKED: 'NOW_DROPDOWN_LIST#ITEM_CLICKED'
};
